// Subelement G4 – Amateur Radio Practices
const g4_questions = [
    // G4A
    {
        question: "What is the purpose of the notch filter found on many HF transceivers?",
        answers: {
            A: "To restrict the transmitter voice bandwidth",
            B: "To reduce interference from carriers in the receiver passband",
            C: "To eliminate receiver interference from impulse noise sources",
            D: "To remove interfering splatter generated by signals on adjacent frequencies"
        },
        correct: "B"
    },
    {
        question: "What is the benefit of using the opposite or “reverse” sideband when receiving CW?",
        answers: {
            A: "Interference from impulse noise will be eliminated",
            B: "More stations can be accommodated within a given signal passband",
            C: "It may be possible to reduce or eliminate interference from other signals",
            D: "Accidental out-of-band operation can be prevented"
        },
        correct: "C"
    },
    {
        question: "How does a noise blanker work?",
        answers: {
            A: "By temporarily increasing received bandwidth",
            B: "By redirecting noise pulses into a filter capacitor",
            C: "By reducing receiver gain during a noise pulse",
            D: "By clipping noise peaks"
        },
        correct: "C"
    },
    {
        question: "What is the effect on plate current of the correct setting of a vacuum-tube RF power amplifier’s TUNE control?",
        answers: {
            A: "A pronounced peak",
            B: "A pronounced dip",
            C: "No change will be observed",
            D: "A slow, rhythmic oscillation"
        },
        correct: "B"
    },
    {
        question: "Why is automatic level control (ALC) used with an RF power amplifier?",
        answers: {
            A: "To balance the transmitter audio frequency response",
            B: "To reduce harmonic radiation",
            C: "To prevent excessive drive",
            D: "To increase overall efficiency"
        },
        correct: "C"
    },
    {
        question: "What is the purpose of an antenna tuner?",
        answers: {
            A: "Reduce the SWR in the feed line to the antenna",
            B: "Reduce the power dissipation in the feedline to the antenna",
            C: "Increase power transfer from the transmitter to the feed line",
            D: "All these choices are correct"
        },
        correct: "D"
    },
    {
        question: "What happens as a receiver’s noise reduction control level is increased?",
        answers: {
            A: "Received signals may become distorted",
            B: "Received frequency may become unstable",
            C: "CW signals may become severely attenuated",
            D: "Received frequency may shift several kHz"
        },
        correct: "A"
    },
    {
        question: "What is the correct adjustment for the LOAD or COUPLING control of a vacuum tube RF power amplifier?",
        answers: {
            A: "Minimum SWR on the antenna",
            B: "Minimum plate current without exceeding maximum allowable grid current",
            C: "Highest plate voltage while minimizing grid current",
            D: "Desired power output without exceeding maximum allowable plate current"
        },
        correct: "D"
    },
    {
        question: "What is the purpose of delaying RF output after activating a transmitter’s keying line to an external amplifier?",
        answers: {
            A: "To prevent key clicks on CW",
            B: "To prevent transient overmodulation",
            C: "To allow time for the amplifier to switch the antenna between the transceiver and the amplifier output",
            D: "To allow time for the amplifier power supply to reach operating level"
        },
        correct: "C"
    },
    {
        question: "What is the function of an electronic keyer?",
        answers: {
            A: "Automatic transmit/receive switching",
            B: "Automatic generation of dots and dashes for CW operation",
            C: "To allow time for switching the antenna from the receiver to the transmitter",
            D: "Computer interface for PSK and RTTY operation"
        },
        correct: "B"
    },
    {
        question: "Why should the ALC system be inactive when transmitting AFSK data signals?",
        answers: {
            A: "ALC will invert the modulation of the AFSK mode",
            B: "The ALC action distorts the signal",
            C: "When using digital modes, too much ALC activity can cause the transmitter to overheat",
            D: "All these choices are correct"
        },
        correct: "B"
    },
    {
        question: "Which of the following is a common use of the dual-VFO feature on a transceiver?",
        answers: {
            A: "To allow transmitting on two frequencies at once",
            B: "To permit full duplex operation -- that is, transmitting and receiving at the same time",
            C: "To transmit on one frequency and listen on another",
            D: "To improve frequency accuracy by allowing variable frequency output (VFO) operation"
        },
        correct: "C"
    },
    {
        question: "What is the purpose of using a receive attenuator?",
        answers: {
            A: "To prevent receiver overload from strong incoming signals",
            B: "To reduce the transmitter power when driving a linear amplifier",
            C: "To reduce power consumption when operating from batteries",
            D: "To reduce excessive audio level on strong signals"
        },
        correct: "A"
    },
    // G4B
    {
        question: "What item of test equipment contains horizontal and vertical channel amplifiers?",
        answers: {
            A: "An ohmmeter",
            B: "A signal generator",
            C: "An ammeter",
            D: "An oscilloscope"
        },
        correct: "D"
    },
    {
        question: "Which of the following is an advantage of an oscilloscope versus a digital voltmeter?",
        answers: {
            A: "An oscilloscope uses less power",
            B: "Complex impedances can be easily measured",
            C: "Greater precision",
            D: "Complex waveforms can be measured"
        },
        correct: "D"
    },
    {
        question: "Which of the following is the best instrument to use for checking the keying waveform of a CW transmitter?",
        answers: {
            A: "An oscilloscope",
            B: "A field strength meter",
            C: "A sidetone monitor",
            D: "A wavemeter"
        },
        correct: "A"
    },
    {
        question: "What signal source is connected to the vertical input of an oscilloscope when checking the RF envelope pattern of a transmitted signal?",
        answers: {
            A: "The local oscillator of the transmitter",
            B: "An external RF oscillator",
            C: "The transmitter balanced mixer output",
            D: "The attenuated RF output of the transmitter"
        },
        correct: "D"
    },
    {
        question: "Why do voltmeters have high input impedance?",
        answers: {
            A: "It improves the frequency response",
            B: "It allows for higher voltages to be safely measured",
            C: "It improves the resolution of the readings",
            D: "It decreases the loading on circuits being measured"
        },
        correct: "D"
    },
    {
        question: "What is an advantage of a digital multimeter as compared to an analog multimeter?",
        answers: {
            A: "Better for measuring computer circuits",
            B: "Less prone to overload",
            C: "Higher precision",
            D: "Faster response"
        },
        correct: "C"
    },
    {
        question: "What signals are used to conduct a two-tone test?",
        answers: {
            A: "Two audio signals of the same frequency shifted 90 degrees",
            B: "Two non-harmonically related audio signals",
            C: "Two swept frequency tones",
            D: "Two audio frequency range square wave signals of equal amplitude"
        },
        correct: "B"
    },
    {
        question: "What transmitter performance parameter does a two-tone test analyze?",
        answers: {
            A: "Linearity",
            B: "Percentage of suppression of the carrier and undesired sideband for SSB",
            C: "Percentage of frequency modulation",
            D: "Percentage of carrier phase shift"
        },
        correct: "A"
    },
    {
        question: "When is an analog multimeter preferred to a digital multimeter?",
        answers: {
            A: "When testing logic circuits",
            B: "When high precision is desired",
            C: "When measuring the frequency of an oscillator",
            D: "When adjusting circuits for maximum or minimum values"
        },
        correct: "D"
    },
    {
        question: "Which of the following can be determined with a directional wattmeter?",
        answers: {
            A: "Standing wave ratio",
            B: "Antenna front-to-back ratio",
            C: "RF interference",
            D: "Radio wave propagation"
        },
        correct: "A"
    },
    {
        question: "Which of the following must be connected to an antenna analyzer when it is being used for SWR measurements?",
        answers: {
            A: "Receiver",
            B: "Transmitter",
            C: "Antenna and feed line",
            D: "All these choices are correct"
        },
        correct: "C"
    },
    {
        question: "What effect can strong signals from nearby transmitters have on an antenna analyzer?",
        answers: {
            A: "Desensitization which can cause intermodulation products which interfere with impedance readings",
            B: "Received power that interferes with SWR readings",
            C: "Generation of harmonics which interfere with frequency readings",
            D: "All these choices are correct"
        },
        correct: "B"
    },
    {
        question: "Which of the following can be measured with an antenna analyzer?",
        answers: {
            A: "Front-to-back ratio of an antenna",
            B: "Power output from a transmitter",
            C: "Impedance of coaxial cable",
            D: "Gain of a directional antenna"
        },
        correct: "C"
    },
    // G4C
    {
        question: "Which of the following might be useful in reducing RF interference to audio frequency circuits?",
        answers: {
            A: "Bypass inductor",
            B: "Bypass capacitor",
            C: "Forward-biased diode",
            D: "Reverse-biased diode"
        },
        correct: "B"
    },
    {
        question: "Which of the following could be a cause of interference covering a wide range of frequencies?",
        answers: {
            A: "Not using a balun or line isolator to feed balanced antennas",
            B: "Lack of rectification of the transmitter’s signal in power conductors",
            C: "Arcing at a poor electrical connection",
            D: "Using a balun to feed an unbalanced antenna"
        },
        correct: "C"
    },
    {
        question: "What sound is heard from an audio device experiencing RF interference from a single sideband phone transmitter?",
        answers: {
            A: "A steady hum whenever the transmitter is on the air",
            B: "On-and-off humming or clicking",
            C: "Distorted speech",
            D: "Clearly audible speech"
        },
        correct: "C"
    },
    {
        question: "What sound is heard from an audio device experiencing RF interference from a CW transmitter?",
        answers: {
            A: "On-and-off humming or clicking",
            B: "A CW signal at a nearly pure audio frequency",
            C: "A chirpy CW signal",
            D: "Severely distorted audio"
        },
        correct: "A"
    },
    {
        question: "What is a possible cause of high voltages that produce RF burns?",
        answers: {
            A: "Flat braid rather than round wire has been used for the ground wire",
            B: "Insulated wire has been used for the ground wire",
            C: "The ground rod is resonant",
            D: "The ground wire has high impedance on that frequency"
        },
        correct: "D"
    },
    {
        question: "What is a possible effect of a resonant ground connection?",
        answers: {
            A: "Overheating of ground straps",
            B: "Corrosion of the ground rod",
            C: "High RF voltages on the enclosures of station equipment",
            D: "A ground loop"
        },
        correct: "C"
    },
    {
        question: "Why should soldered joints not be used in lightning protection ground connections?",
        answers: {
            A: "A soldered joint will likely be destroyed by the heat of a lightning strike",
            B: "Solder flux will prevent a low conductivity connection",
            C: "Solder has too high a dielectric constant to provide adequate lightning protection",
            D: "All these choices are correct"
        },
        correct: "A"
    },
    {
        question: "Which of the following would reduce RF interference caused by common-mode current on an audio cable?",
        answers: {
            A: "Place a ferrite choke on the cable",
            B: "Connect the center conductor to the shield of all cables to short circuit the RFI signal",
            C: "Ground the center conductor of the audio cable causing the interference",
            D: "Add an additional insulating jacket to the cable"
        },
        correct: "A"
    },
    {
        question: "How can the effects of ground loops be minimized?",
        answers: {
            A: "Connect all ground conductors in series",
            B: "Connect the AC neutral conductor to the ground wire",
            C: "Avoid using lock washers and star washers when making ground connections",
            D: "Bond equipment enclosures together"
        },
        correct: "D"
    },
    {
        question: "What could be a symptom caused by a ground loop in your station’s audio connections?",
        answers: {
            A: "You receive reports of “hum” on your station’s transmitted signal",
            B: "The SWR reading for one or more antennas is suddenly very high",
            C: "An item of station equipment starts to draw excessive amounts of current",
            D: "You receive reports of harmonic interference from your station"
        },
        correct: "A"
    },
    {
        question: "What technique helps to minimize RF “hot spots” in an amateur station?",
        answers: {
            A: "Building all equipment in a metal enclosure",
            B: "Using surge suppressor power outlets",
            C: "Bonding all equipment enclosures together",
            D: "Placing low-pass filters on all feed lines"
        },
        correct: "C"
    },
    {
        question: "Why must all metal enclosures of station equipment be grounded?",
        answers: {
            A: "It prevents a blown fuse in the event of an internal short circuit",
            B: "It prevents signal overload",
            C: "It ensures that the neutral wire is grounded",
            D: "It ensures that hazardous voltages cannot appear on the chassis"
        },
        correct: "D"
    },
    // G4D
    {
        question: "What is the purpose of a speech processor in a transceiver?",
        answers: {
            A: "Increase the apparent loudness of transmitted voice signals",
            B: "Increase transmitter bass response for more natural-sounding SSB signals",
            C: "Prevent distortion of voice signals",
            D: "Decrease high-frequency voice output to prevent out-of-band operation"
        },
        correct: "A"
    },
    {
        question: "How does a speech processor affect a single sideband phone signal?",
        answers: {
            A: "It increases peak power",
            B: "It increases average power",
            C: "It reduces harmonic distortion",
            D: "It reduces intermodulation distortion"
        },
        correct: "B"
    },
    {
        question: "What is the effect of an incorrectly adjusted speech processor?",
        answers: {
            A: "Distorted speech",
            B: "Excess intermodulation products",
            C: "Excessive background noise",
            D: "All these choices are correct"
        },
        correct: "D"
    },
    {
        question: "What does an S meter measure?",
        answers: {
            A: "Carrier suppression",
            B: "Impedance",
            C: "Received signal strength",
            D: "Transmitter power output"
        },
        correct: "C"
    },
    {
        question: "How does a signal that reads 20 dB over S9 compare to one that reads S9 on a receiver, assuming a properly calibrated S meter?",
        answers: {
            A: "It is 10 times less powerful",
            B: "It is 20 times less powerful",
            C: "It is 20 times more powerful",
            D: "It is 100 times more powerful"
        },
        correct: "D"
    },
    {
        question: "How much change in signal strength is typically represented by one S unit?",
        answers: {
            A: "6 dB",
            B: "12 dB",
            C: "15 dB",
            D: "18 dB"
        },
        correct: "A"
    },
    {
        question: "How much must the power output of a transmitter be raised to change the S meter reading on a distant receiver from S8 to S9?",
        answers: {
            A: "Approximately 1.5 times",
            B: "Approximately 2 times",
            C: "Approximately 4 times",
            D: "Approximately 8 times"
        },
        correct: "C"
    },
    {
        question: "What frequency range is occupied by a 3 kHz LSB signal when the displayed carrier frequency is set to 7.178 MHz?",
        answers: {
            A: "7.178 MHz to 7.181 MHz",
            B: "7.178 MHz to 7.184 MHz",
            C: "7.175 MHz to 7.178 MHz",
            D: "7.1765 MHz to 7.1795 MHz"
        },
        correct: "C"
    },
    {
        question: "What frequency range is occupied by a 3 kHz USB signal with the displayed carrier frequency set to 14.347 MHz?",
        answers: {
            A: "14.347 MHz to 14.647 MHz",
            B: "14.347 MHz to 14.350 MHz",
            C: "14.344 MHz to 14.347 MHz",
            D: "14.3455 MHz to 14.3485 MHz"
        },
        correct: "B"
    },
    {
        question: "How close to the lower edge of a band’s phone segment should your displayed carrier frequency be when using 3 kHz wide LSB?",
        answers: {
            A: "At least 3 kHz above the edge of the segment",
            B: "At least 3 kHz below the edge of the segment",
            C: "At least 1 kHz below the edge of the segment",
            D: "At least 1 kHz above the edge of the segment"
        },
        correct: "A"
    },
    {
        question: "How close to the upper edge of a band’s phone segment should your displayed carrier frequency be when using 3 kHz wide USB?",
        answers: {
            A: "At least 3 kHz above the edge of the band",
            B: "At least 3 kHz below the edge of the band",
            C: "At least 1 kHz above the edge of the segment",
            D: "At least 1 kHz below the edge of the segment"
        },
        correct: "B"
    },
    // G4E
    {
        question: "What is the purpose of a capacitance hat on a mobile antenna?",
        answers: {
            A: "To increase the power handling capacity of a whip antenna",
            B: "To reduce radiation resistance",
            C: "To electrically lengthen a physically short antenna",
            D: "To lower the radiation angle"
        },
        correct: "C"
    },
    {
        question: "What is the purpose of a corona ball on an HF mobile antenna?",
        answers: {
            A: "To narrow the operating bandwidth of the antenna",
            B: "To increase the “Q” of the antenna",
            C: "To reduce the chance of damage if the antenna should strike an object",
            D: "To reduce RF voltage discharge from the tip of the antenna while transmitting"
        },
        correct: "D"
    },
    {
        question: "Which of the following direct, fused power connections would be the best for a 100-watt HF mobile installation?",
        answers: {
            A: "To the battery using heavy-gauge wire",
            B: "To the alternator or generator using heavy-gauge wire",
            C: "To the battery using insulated heavy duty balanced transmission line",
            D: "To the alternator or generator using insulated heavy duty balanced transmission line"
        },
        correct: "A"
    },
    {
        question: "Why should DC power for a 100-watt HF transceiver not be supplied by a vehicle’s auxiliary power socket?",
        answers: {
            A: "The socket is not wired with an RF-shielded power cable",
            B: "The socket’s wiring may be inadequate for the current drawn by the transceiver",
            C: "The DC polarity of the socket is reversed from the polarity of modern HF transceivers",
            D: "Drawing more than 50 watts from this socket could cause the engine to overheat"
        },
        correct: "B"
    },
    {
        question: "Which of the following most limits an HF mobile installation?",
        answers: {
            A: "“Picket fencing”",
            B: "The wire gauge of the DC power line to the transceiver",
            C: "Efficiency of the electrically short antenna",
            D: "FCC rules limiting mobile output power on the 75-meter band"
        },
        correct: "C"
    },
    {
        question: "What is one disadvantage of using a shortened mobile antenna as opposed to a full-size antenna?",
        answers: {
            A: "Short antennas are more likely to cause distortion of transmitted signals",
            B: "Q of the antenna will be very low",
            C: "Operating bandwidth may be very limited",
            D: "Harmonic radiation may increase"
        },
        correct: "C"
    },
    {
        question: "Which of the following may cause receive interference to an HF transceiver installed in a vehicle?",
        answers: {
            A: "The battery charging system",
            B: "The fuel delivery system",
            C: "The control computers",
            D: "All these choices are correct"
        },
        correct: "D"
    },
    {
        question: "In what configuration are the individual cells in a solar panel connected together?",
        answers: {
            A: "Series-parallel",
            B: "Shunt",
            C: "Bypass",
            D: "Full-wave bridge"
        },
        correct: "A"
    },
    {
        question: "What is the approximate open-circuit voltage from a fully illuminated silicon photovoltaic cell?",
        answers: {
            A: "0.02 VDC",
            B: "0.5 VDC",
            C: "0.2 VDC",
            D: "1.38 VDC"
        },
        correct: "B"
    },
    {
        question: "Why should a series diode be connected between a solar panel and a storage battery that is being charged by the panel?",
        answers: {
            A: "To prevent overload by regulating the charging voltage",
            B: "To prevent discharge of the battery through the panel during times of low or no illumination",
            C: "To limit the current flowing from the panel to a safe value",
            D: "To prevent damage to the battery due to excessive voltage at high illumination levels"
        },
        correct: "B"
    },
    {
        question: "What precaution should be taken when connecting a solar panel to a lithium iron phosphate battery?",
        answers: {
            A: "Ground the solar panel outer metal framework",
            B: "Ensure the battery is placed terminals-up",
            C: "A series resistor must be in place",
            D: "The solar panel must have a charge controller"
        },
        correct: "D"
    }
];